sudo: required
language: node_js
node_js:
  - "9"

script:
  - npm config set registry https://registry.npm.taobao.org
  - npm run build
  - npm test -- --coverage

after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov -t ef6f1b41-9df2-40b1-bee8-81b8ca6f143a

